spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddfinance?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

mybatis:
  type-aliases-package: com.zyc.api.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /ding


